# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: English Remediation
email: your-email@domain.com
author: Theodore Chiu
description: > # this means to ignore newlines until "baseurl:"
  Theo's Blog
  
baseurl: "/englblog/" # the subpath of your site, e.g. /blog
url: "http://theochiu.github.io" # the base hostname & protocol for your site
rmeote_theme: jekyll-theme-awesome
twitter_username: jekyllrb
github_username:  jekyll
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Build settings
markdown: kramdown
